---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Install bind-utils
    yum:
      name: bind
      state: latest
    when: ansible_connection == 'local'

  - name: Edit file 
    lineinfile:
      path: /etc/named.conf
      regexp: 'listen-on port 53 { 127.0.0.1; };'
      line: 'listen-on port 53 { 127.0.0.1; 192.168.100.11; };'
      backup: yes
    when: ansible_connection == 'local'

  - name: Edit nameserver allow query 
    lineinfile:
      path: /etc/named.conf
      regexp: 'allow-query     { localhost; };'
      line: 'allow-query     { any; };'
      backup: yes
    when: ansible_connection == 'local'

  - name: Include named local
    lineinfile:
      path: /etc/named.conf
      line: 'include "/etc/named/named.conf.local";'
      backup: yes
    when: ansible_connection == 'local'

  - name: Copy named.con.local file 
    template:
      src: template/named.conf.local.j2
      dest: /etc/named/named.conf.local
      owner: root
      group: root
      mode: 0755
    when: ansible_connection == 'local'

  - name: Create Zones
    file:
      path: /etc/named/zones
      state: directory
      mode: 0755
    when: ansible_connection == 'local'

  - name: Copy Zone file
    template:
      src: '{{ item.source }}'
      dest: '{{ item.destination }}'
      owner: root
      group: root
      mode: "0755"
    loop:
      - { source: 'template/db.mynet-864.com.j2', destination: '/etc/named/zones/db.mynet-864.com' }
      - { source: 'template/db.192.168.100.j2', destination: '/etc/named/zones/db.192.168.100' }
      - { source: 'template/db.my-site.com.j2', destination: '/etc/named/zones/db.my-site.com' }
    when: ansible_connection == 'local'

 
  - name: Start service
    service:
      name: named
      state: started
    when: ansible_connection == 'local'

  - name: Start firewalld
    service:
      name: firewalld
      state: started	
    when: ansible_connection == 'local'

  - name: Open firewalld
    firewalld:
      port: '{{ item }}'
      permanent: yes
      state: enabled
    loop:
      - "53/udp" 
      - "53/tcp" 
    when: ansible_connection == 'local'
   

  - name: Start firewalld
    service:
      name: firewalld
      state: restarted	
    when: ansible_connection == 'local'

  - name: Copy resolv file 
    template:
      src: template/resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: "0644"

  - name: Install Bind-Utils all Server
    yum:
      name: bind-utils
      state: latest

- hosts: web
  become: yes
  become_user: root
  tasks:
 
  - name: Install remi repo.
    yum:
      name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
      state: present

  - name: Import remi GPG key.
    rpm_key:
      key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
      state: present

  - name: Install httpd and php 7.3 and php module
    yum:
      name:
        - httpd
        - php
        - php-mysqlnd
        - php-curl 
      state: latest
      enablerepo: remi-php73

  - name: Edit file Timezone
    lineinfile:
      path: /etc/php.ini
      regexp: ';date.timezone'
      line: 'date.timezone = Asia/Bangkok'
      backup: yes
    
  - name: Enable service httpd
    service:
      name: httpd
      enabled: yes

  - name: Start service httpd
    service:
      name: httpd
      state: started

  - name: Enable firewall
    service:
      name: firewalld
      enabled: yes

  - name: Start firewall
    service:
      name: firewalld
      state: started

  - name: Open firewalld service http and https
    firewalld:
      service: '{{ item }}'
      permanent: yes
      state: enabled
    loop:
      - "http" 
      - "https" 
 
  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted	

- hosts: db
  become: yes
  become_user: root
  tasks:

  - name: Install nfs-utils
    yum:
      name: nfs-utils
      state: latest

  - name: edit file exportd
    lineinfile:
      path: /etc/exports
      line: '/var/nfs    *(rw,sync,no_root_squash,no_all_squash)'

  - name: Create dir nfs
    file:
      path: '/var/nfs'
      state: directory
      owner: nfsnobody
      group: nfsnobody
      mode: 0755
  
  - name: Enable service rpcbind
    service:
      name: rpcbind
      enabled: yes
  - name: Enable service nfs-server
    service:
      name: nfs-server
      enabled: yes
  - name: Enable service nfs-lock
    service:
      name: nfs-lock
      enabled: yes

  - name: started service rpcbind
    service:
      name: rpcbind
      state: started	
  - name: started service nfs-server
    service:
      name: nfs-server
      state: started	
  - name: started service nfs-lock
    service:
      name: nfs-lock
      state: started	

  - name: Open firewalld service mountd and rcp-bind
    firewalld:
      service: '{{ item }}'
      permanent: yes
      state: enabled
    loop:
      - "mountd" 
      - "rpc-bind"
      - "nfs"

  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted

- hosts: web
  become: yes
  become_user: root
  tasks:

  - name: Install nfs-utils
    yum:
      name: nfs-utils
      state: latest

  - name: Create dir nfs/www
    file:
      path: '/var/nfs/www'
      state: directory
      mode: 0755

  - name: Create dir log 864
    file:
      path: '/var/nfs/www/mynet-864.com/log'
      state: directory
      mode: 0755

  - name: Create dir html 864
    file:
      path: '/var/nfs/www/mynet-864.com/html'
      state: directory
      mode: 0755

  - name: Create dir log site
    file:
      path: '/var/nfs/www/my-site.com/log'
      state: directory
      mode: 0755

  - name: Create dir html site
    file:
      path: '/var/nfs/www/my-site.com/html'
      state: directory
      mode: 0755

  - name: Copy file conf web-01
    template:
      src: '{{ item.source }}'
      dest: '{{ item.destination }}'
      owner: root
      group: root
      mode: "0755"
    loop:
      - { source: 'template/my-site-01.com.conf.j2', destination: '/etc/httpd/conf.d/my-site.com.conf' }
      - { source: 'template/mynet-864-01.com.conf.j2', destination: '/etc/httpd/conf.d/mynet-864.com.conf' }
    when: ansible_ssh_host == '192.168.100.81'
  
  - name: Copy file conf web-02
    template:
      src: '{{ item.source }}'
      dest: '{{ item.destination }}'
      owner: root
      group: root
      mode: "0755"
    loop:
      - { source: 'template/my-site-02.com.conf.j2', destination: '/etc/httpd/conf.d/my-site.com.conf' }
      - { source: 'template/mynet-864-02.com.conf.j2', destination: '/etc/httpd/conf.d/mynet-864.com.conf' }
    when: ansible_ssh_host == '192.168.100.82'

  #- name: Mount 
  # command: mount 192.168.100.70:/var/nfs /var/nfs/www


  - name: Restart service httpd
    service:
      name: httpd
      state: restarted

  - name: Copy index.php to web.server
    template:
      src: template/index.php.j2
      dest: /var/nfs/www/my-site.com/html/index.php
      owner: nfsnobody
      group: nfsnobody
      mode: 0755

  - name: Copy index.php to web.server
    template:
      src: template/index.php.j2
      dest: /var/nfs/www/mynet-864.com/html/index.php
      owner: nfsnobody
      group: nfsnobody
      mode: 0755


- hosts: lb
  become: yes
  become_user: root
  tasks:

  - name: Install nginx
    yum: 
      name: nginx  
      state: latest

  - name: Start nginx 
    service: 
      name: nginx
      state: started
  
  - name: Enable nginx 
    service: 
      name: nginx
      enabled: yes    
  
  - name: Start firewalld 
    service: 
      name: firewalld
      state: started
  
  - name: Enable firewalld 
    service: 
      name: firewalld
      enabled: yes    
  
  - name: Open firewalld service nginx
    firewalld:
      service: '{{ item }}'
      permanent: yes
      state: enabled
    loop:
      - "http" 
  
  - name: Open firewalld service nginx
    firewalld:
      port: '{{ item }}'
      permanent: yes
      state: enabled
    loop:
      - "80/tcp" 
  
  - name: Copy file conf 
    template:
      src: '{{ item.source }}'
      dest: '{{ item.destination }}'
      owner: root
      group: root
      mode: "0755"
    loop:
      - { source: 'template/my-site.conf.j2', destination: '/etc/nginx/conf.d/my-site.conf' }
      - { source: 'template/mynet.conf.j2', destination: '/etc/nginx/conf.d/mynet.conf' }
    
  
  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted    

  - name: Restart nginx
    service:
      name: nginx
      state: restarted   

- hosts: all
  become: yes
  become_user: root
  tasks:

  - name: Install rsyslog
    yum:
     name: rsyslog
     state: latest

  - name: Enable service rsyslog
    service:
        name: rsyslog
        enabled: yes

  - name: Start rsyslog
    service:
        name: rsyslog
        state: started  

  - name: Copy rsyslog.conf
    template:
     src: template/rsyslog1.conf.j2
     dest: /etc/rsyslog.conf
     owner: root
     group: root
     mode: 0755
    when: ansible_connection == 'local'

  - name: Copy rsyslog2.conf client
    template:
     src: template/rsyslog2.conf.j2
     dest: /etc/rsyslog.conf
     owner: root
     group: root
     mode: 0755
    when: ansible_ssh_host == '192.168.100.70'

  - name: Copy rsyslog2.conf webserver
    template:
     src: template/rsyslog2.conf.j2
     dest: /etc/rsyslog.conf
     owner: root
     group: root
     mode: 0755
    when: ansible_ssh_host == '192.168.100.81'

  - name: Copy rsyslog2.conf webserver
    template:
     src: template/rsyslog2.conf.j2
     dest: /etc/rsyslog.conf
     owner: root
     group: root
     mode: 0755
    when: ansible_ssh_host == '192.168.100.82'

  - name: Copy rsyslog2.conf lb
    template:
     src: template/rsyslog2.conf.j2
     dest: /etc/rsyslog.conf
     owner: root
     group: root
     mode: 0755
    when: ansible_ssh_host == '192.168.100.80'

  - name: Open port firewall 514
    firewalld:
        port: "514/tcp"
        permanent: yes
        state: enabled

  - name: Open port firewall 514
    firewalld:
        port: "514/udp"
        permanent: yes
        state: enabled

  - name: reStart firewall
    service:
        name: firewalld
        state: restarted  
  - name: reStart rsyslog
    service:
        name: rsyslog
        state: restarted  
