---
- hosts: myserver
  become: yes
  become_user: root
  tasks:
  - name: Install NTP Server
    yum: name=ntp state=latest
  - name:
    lineinfile: path=/etc/ntp.conf regexp='^#restrict 192.168.1.0' line='restrict 192.168.100.0 mask 255.255.255.0 nomodify notrap'
  - name:
    lineinfile: path=/etc/ntp.conf regexp='^server 0' line='server 3.th.pool.ntp.org iburst'
  - name:
    lineinfile: path=/etc/ntp.conf regexp='^server 1' line=''
  - name:
    lineinfile: path=/etc/ntp.conf regexp='^server 2' line=''
  - name:
    lineinfile: path=/etc/ntp.conf regexp='^server 3' line=''
  - name: Install firewalld
    yum: name=firewalld state=latest
    
  - name: Start firewalld
    service: name=firewalld state=started 
  - name: Open firewall
    firewalld: service=ntp permanent=yes state=enabled
  - name: Restart firewalld
    service: name=firewalld state=restarted
  - name: set timezone to Asia/Bangkok
    timezone: name=Asia/Bangkok